#!/usr/bin/env bash
# dispaly users and their id and group

# lines=$(cat /etc/passwd | wc -l)
lines="$(cat < input | wc -l)"
i="1"

while [ $i -le "$lines" ]; do
	line=$(cat < input | head -n $i | tail -n 1)
	array="${line// /_}"
	IFS=":" read -r -a array <<< "$array"
	echo "${array[0]}:${array[2]}:${array[5]}"
	i=$((i+1))
done

# root:x:0:0:root:/root:/bin/bash -> root:0:/root
# arrIN=(${IN//;/ })
